import { afterEach, expect, it } from "vitest";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRuntimeFromPath } from "../../src/runtime.js";
import { FIXTURE, seedFixture } from "../../src/bootstrap/seed.js";
import { startCampfireHttpServer } from "../../src/http/server.js";
import { campfireHttpCall, campfireHttpRedeemEnrollment } from "../../src/http/client.js";
import { hashToken } from "../../src/service/tokens.js";
const cleanup: Array<() => void | Promise<void>> = [];
afterEach(async () => { for (const close of cleanup.reverse()) await close(); cleanup.length = 0; });
it("keeps redemption separate from actor calls and returns stable credentials on exact retry", async () => {
  const dir = mkdtempSync(join(tmpdir(), "enrollment-http-"));
  const runtime = createRuntimeFromPath(join(dir, "state.db"));
  seedFixture(runtime.store);
  const server = await startCampfireHttpServer({ runtime, port: 0 });
  cleanup.push(() => rmSync(dir, {recursive:true,force:true}), () => runtime.close(), () => server.close());
  const invitation = await campfireHttpCall<any>({baseUrl:server.url,token:FIXTURE.tokens.sergio,method:"issue_enrollment_invitation",params:{workspaceId:FIXTURE.workspaces.billing}});
  const input = {invitationId:invitation.invitationId,requestId:"req_http",humanName:"Teammate",humanTokenHash:hashToken("human-prepared"),agents:[{harness:"opencode" as const,tokenHash:hashToken("agent-prepared")}]};
  await expect(campfireHttpCall({baseUrl:server.url,token:invitation.secret,method:"whoami"})).rejects.toMatchObject({code:"Unauthorized"});
  const receipt = await campfireHttpRedeemEnrollment({baseUrl:server.url,secret:invitation.secret,input});
  expect(await campfireHttpRedeemEnrollment({baseUrl:server.url,secret:invitation.secret,input})).toEqual(receipt);
  expect(await campfireHttpCall({baseUrl:server.url,token:"human-prepared",method:"whoami"})).toMatchObject({actor:{actorId:receipt.human.id,actorType:"human"}});
  await expect(campfireHttpRedeemEnrollment({baseUrl:server.url,secret:invitation.secret,input:{...input,role:"owner"} as any})).rejects.toMatchObject({code:"ValidationError"});
  const viewer = await fetch(`${server.url}/v1/call`, {method:"POST",headers:{authorization:`Bearer ${invitation.secret}`,"content-type":"application/json"},body:JSON.stringify({method:"redeem_enrollment",params:input})});
  expect(viewer.status).toBe(400);
});

it("finishes the recipient profile and two-agent continuity without a local database", async () => {
  const { joinFromInvitation, enrollRemoteAgent, saveInvitationFile } = await import("../../src/bootstrap/enrollment-client.js");
  const { loadRemoteProfile, resolveRemoteAccess } = await import("../../src/bootstrap/remote-profile.js");
  const { resolveProfilePaths } = await import("../../src/bootstrap/profile.js");
  const { existsSync } = await import("node:fs");
  const dir = mkdtempSync(join(tmpdir(), "enrollment-journey-"));
  const env:NodeJS.ProcessEnv = {...process.env, CAMPFIRE_CONFIG_DIR:join(dir,"recipient"), CAMPFIRE_DATA_DIR:join(dir,"recipient-data"), HOME:join(dir,"home"), XDG_CONFIG_HOME:join(dir,"xdg")};
  delete env.CAMPFIRE_URL; delete env.CAMPFIRE_TOKEN;
  const runtime=createRuntimeFromPath(join(dir,"owner.db")); seedFixture(runtime.store);
  const server=await startCampfireHttpServer({runtime,port:0});
  cleanup.push(()=>rmSync(dir,{recursive:true,force:true}),()=>runtime.close(),()=>server.close());
  const invitation=await campfireHttpCall<any>({baseUrl:server.url,token:FIXTURE.tokens.sergio,method:"issue_enrollment_invitation",params:{workspaceId:FIXTURE.workspaces.billing}});
  const file=join(dir,"private-invitation.json"); saveInvitationFile(file,invitation,server.url,true);
  const receipt=await joinFromInvitation({invitationFile:file,humanName:"New Teammate",harnesses:["opencode"],allowLoopback:true},env);
  expect(loadRemoteProfile(env)?.humanId).toBe(receipt.human.id);
  expect(existsSync(resolveProfilePaths(env).defaultDatabasePath)).toBe(false);
  expect(existsSync(join(resolveProfilePaths(env).configDir,"pending-enrollment.json"))).toBe(false);
  const second=await enrollRemoteAgent({harness:"codex"},env);
  expect(second.humanId).toBe(receipt.human.id);
  expect(loadRemoteProfile(env)?.agents).toHaveLength(2);
  const access=resolveRemoteAccess({harness:"opencode"},env);
  const call=(method:string,params:Record<string,unknown>={})=>campfireHttpCall<any>({baseUrl:access.url,token:access.token,method,params});
  await expect(call("add_finding",{workspaceId:receipt.workspace.id,summary:"Without session",detail:"Rejected"})).rejects.toMatchObject({code:"Unauthorized"});
  const session=await call("register_agent_session",{workspaceId:receipt.workspace.id,harness:"opencode"});
  const finding=await call("add_finding",{workspaceId:receipt.workspace.id,summary:"Recipient contribution",detail:"Verified existing context",agentSessionId:session.id});
  const context=await campfireHttpCall<any>({baseUrl:server.url,token:FIXTURE.tokens.sergio,method:"get_workspace_context",params:{workspaceId:receipt.workspace.id}});
  expect(context.findings.some((entry:any)=>entry.id===finding.id)).toBe(true);
});
